
const fs = require('fs');
const path = require('path');

// [Gate] Contract Verification
// Ensures the final variant contains mandatory fields that are NOT generated by LLM but injected by normalizer.

const REQUIRED_KEYS = [
    'HEADLINE',
    'SUBHEAD',
    'BENEFIT_BULLETS',
    'CTA',
    'info',
    'INFO',
    'offerBlock'
];

function verifyContract(variant, traceId = "test") {
    const missing = REQUIRED_KEYS.filter(k => !variant[k]);
    if (missing.length > 0) {
        console.error(`[FAIL] Trace ${traceId}: Missing contracted keys: ${missing.join(", ")}`);
        return false;
    }

    if (!variant.info.includes("/") || !variant.INFO.includes("/")) {
        console.error(`[FAIL] Trace ${traceId}: INFO field missing normalization separator "/"`);
        return false;
    }

    return true;
}

// Logic to load some mock engine results or run a live test if possible
console.log("[Gate] verify_contract.js: Universal Contract Validation Loaded.");
module.exports = { verifyContract };
